### ISSUE TITLE
Title isn't shown instead "Oops, an error occurred"

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1714]
This one isn't shown as single hit:
https://alma.lobid.org/resources/990054518430206441
Data ist there (append `.json):` https://alma.lobid.org/resources/990054518430206441.json

@blackwinter  points out that this resource  has 2k items, and that seems to be in fact the problem:

```
! @81boda180 - Internal server error, for (GET) [/resources/990054518430206441] ->

play.api.UnexpectedException: Unexpected exception[ArrayIndexOutOfBoundsException: 1]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
     [...]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at controllers.resources.Lobid.compareIsil(Lobid.java:409) ~[lobid-resources-web.lobid-resources-web-0.2.2-SNAPSHOT-sans-externalized.jar:na]
        at views.html.tags.items_map_Scope0$items_map$$anonfun$markers$1$1.apply(items_map.template.scala:46) ~[lobid-resources-web.lobid-resources-web-0.2.2-SNAPSHOT-sans-externalized.jar:na]
        at views.html.tags.items_map_Scope0$items_map$$anonfun$markers$1$1.apply(items_map.template.scala:46) ~[lobid-resources-web.lobid-resources-web-0.2.2-SNAPSHOT-sans-externalized.jar:na]
        at scala.math.Ordering$$anon$9.compare(Ordering.scala:200) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at java.util.TimSort.binarySort(TimSort.java:296) ~[na:1.8.0_151]
        at java.util.TimSort.sort(TimSort.java:239) ~[na:1.8.0_151]
        at java.util.Arrays.sort(Arrays.java:1438) ~[na:1.8.0_151]
        at scala.collection.SeqLike$class.sorted(SeqLike.scala:648) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.collection.AbstractSeq.sorted(Seq.scala:41) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.collection.SeqLike$class.sortWith(SeqLike.scala:601) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.collection.AbstractSeq.sortWith(Seq.scala:41) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at views.html.tags.items_map_Scope0$items_map.markers$1(items_map.template.scala:46) ~[lobid-resources-web.lobid-resources-web-0.2.2-SNAPSHOT-sans-externalized.jar:na]
        at views.html.tags.items_map_Scope0$items_map.apply(items_map.template.scala:157) ~[lobid-resources-web.lobid-resources-web-0.2.2-SNAPSHOT-sans-externalized.jar:na]

```

**Comment by dr0i** [comment]
> test.lobid.org may still be based on the NZ phase 1 publishing (w/o IZ bridges).

right! We may want to switch this?

**Comment by dr0i** [comment]
Discussed with @fsteeg: we don't switch ( i.e. we don't configure test.lobid.org to the same index as alma.lobid.org) . So we ensure stability for testing http://test.nwbib.de/ (which uses test.lobid.org) .  _After_ this issue here is fixed for alma.lobid.org we will use alma.lobid.org as base API for http://test.nwbib.de/ .

**Comment by fsteeg** [comment]
Deployed to test (and with a slight tweak to the plan, as discussed with @dr0i, switched test to `resources-alma-fix`):

https://test.lobid.org/resources/990054518430206441

And thanks for the pointer to the underlying issue, @blackwinter!
