### ISSUE TITLE
`play.api.UnexpectedException: Unexpected exception[RuntimeException: com.fasterxml.jackson.core.JsonParseException`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1851]
2023-07-29 13:47:08 +0200 [ERROR] from application in application-akka.actor.default-dispatcher-49 - 

! @82cke49l3 - Internal server error, for (GET) [/resources/facets?q=&agent=&name=&subject=&publisher=&issued=1790&medium=&from=0&size=15&owner=&t=&field=owner&sort=&word=] ->
 
play.api.UnexpectedException: Unexpected exception[RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"

<!DOCTYPE html>

<html lang="de">
    <head>
        <title>Error</title>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/bootstrap.min.css"/>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/octicons.css"/>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/jquery-ui.min.css"/>
        <link rel="stylesheet" media="all" href='/resources/assets/stylesheets/font-awesome.min.css'/>
        <link rel="styl"[truncated 5274 chars]; line: 6, column: 2]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.11.jar:na]
	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play.play-netty-server_2.11-2.4.11.jar:2.4.11]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play.play-netty-server_2.11-2.4.11.jar:2.4.11]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36) [org.scala-lang.scala-library-2.11.11.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play.play-iteratees_2.11-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play.play-iteratees_2.11-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36) [org.scala-lang.scala-library-2.11.11.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.11.jar:na]
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"

<!DOCTYPE html>

<html lang="de">
    <head>
        <title>Error</title>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/bootstrap.min.css"/>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/octicons.css"/>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/jquery-ui.min.css"/>
        <link rel="stylesheet" media="all" href='/resources/assets/stylesheets/font-awesome.min.css'/>
        <link rel="styl"[truncated 5274 chars]; line: 6, column: 2]
	at play.libs.Json.parse(Json.java:138) ~[com.typesafe.play.play-json_2.11-2.4.11.jar:2.4.11]
	at controllers.resources.Application.lambda$facets$26(Application.java:717) ~[lobid-resources-web.lobid-resources-web-0.3.0-SNAPSHOT-sans-externalized.jar:na]
	at play.core.j.FPromiseHelper$$anonfun$map$1.apply(FPromiseHelper.scala:103) ~[com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.11.jar:na]
	at scala.util.Success.map(Try.scala:237) ~[org.scala-lang.scala-library-2.11.11.jar:na]
	... 10 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"

<!DOCTYPE html>

<html lang="de">
    <head>
        <title>Error</title>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/bootstrap.min.css"/>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/octicons.css"/>
        <link rel="stylesheet" media="all" href="/resources/assets/stylesheets/jquery-ui.min.css"/>
        <link rel="stylesheet" media="all" href='/resources/assets/stylesheets/font-awesome.min.css'/>
        <link rel="styl"[truncated 5274 chars]; line: 6, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418) ~[com.fasterxml.jackson.core.jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:749) ~[com.fasterxml.jackson.core.jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:673) ~[com.fasterxml.jackson.core.jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2082) ~[com.fasterxml.jackson.core.jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:805) ~[com.fasterxml.jackson.core.jackson-core-2.14.2.jar:2.14.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4622) ~[com.fasterxml.jackson.core.jackson-databind-2.12.7.1.jar:2.12.7.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3042) ~[com.fasterxml.jackson.core.jackson-databind-2.12.7.1.jar:2.12.7.1]
	at play.libs.Json.parse(Json.java:136) ~[com.typesafe.play.play-json_2.11-2.4.11.jar:2.4.11]
	... 15 common frames omitted

**Comment by TobiasNx** [comment]
Closing this ticket for now, since we did not encounter this problem again.
