### ISSUE TITLE
Error on test API page

### ISSUE THREAD

**Issue by Phu2** [hbz/lobid-resources#1900]
http://test.lobid.org/resources/api is showing an error, eg. "This exception has been logged with id 8324hg7nl."

From `web/logs/application.log`:
```
2023-09-22 14:22:39 +0200 [ERROR] from application in application-akka.actor.default-dispatcher-2 -

! @8324hg7nl - Internal server error, for (GET) [/resources/api] ->

play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.11.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play.play-netty-server_2.11-2.4.11.jar:2.4.11]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play.play-netty-server_2.11-2.4.11.jar:2.4.11]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.util.Failure.recover(Try.scala:216) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36) [org.scala-lang.scala-library-2.11.11.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play.play-iteratees_2.11-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play.play-iteratees_2.11-2.4.11.jar:2.4.11]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.11.11.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.11.jar:na]
Caused by: java.lang.NullPointerException: null
        at views.html.api_Scope0$api.sample_doc$1(api.template.scala:40) ~[lobid-resources-web.lobid-resources-web-0.3.0-SNAPSHOT-sans-externalized.jar:na]
        at views.html.api_Scope0$api.apply(api.template.scala:159) ~[lobid-resources-web.lobid-resources-web-0.3.0-SNAPSHOT-sans-externalized.jar:na]
        at views.html.api_Scope0$api.render(api.template.scala:173) ~[lobid-resources-web.lobid-resources-web-0.3.0-SNAPSHOT-sans-externalized.jar:na]
        at views.html.api.render(api.template.scala) ~[lobid-resources-web.lobid-resources-web-0.3.0-SNAPSHOT-sans-externalized.jar:na]
        at controllers.resources.Application.lambda$api$1(Application.java:143) ~[lobid-resources-web.lobid-resources-web-0.3.0-SNAPSHOT-sans-externalized.jar:na]
        at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36) ~[com.typesafe.play.play_2.11-2.4.11.jar:2.4.11]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.11.11.jar:na]
        ... 7 common frames omitted
2023-09-22 14:49:28 +0200 [ERROR] from application in application-akka.actor.default-dispatcher-7 -
```

**Comment by Phu2** [comment]
It works again. After updating the sources from git, starting a new build and setting the correct index in `web/conf/resources.conf`. Thanks, @dr0i !
