### ISSUE TITLE
Resources in log without hbzId?

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#743]
```
--
WARN - Model without subject - skipping. Model size=202
[...]
WARN - Model without subject - skipping. Model size=202
ERROR - Exception in _:BX5FX3AhttpX3AX2FX2FschemaX2EorgX2Fpublication33484498 <http://schema.org/publishedBy> "Stollfuss" .
_:BX5FX3AhttpX3AX2FX2FschemaX2EorgX2Fpublication33484498 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/PublicationEvent> .
_:BX5FX3AhttpX3AX2FX2FschemaX2EorgX2Fpublication33484498 <http://schema.org/location> "Bonn" .
<dummy_subject> <http://schema.org/publication> _:BX5FX3AhttpX3AX2FX2FschemaX2EorgX2Fpublication33484498 .
<dummy_subject> <http://purl.org/dc/terms/title> "Zeitschrift f\u00FCr Z\u00F6lle und Verbrauchsteuern" .
<dummy_subject> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/lobid/lv#Miscellaneous> .
<dummy_subject> <http://purl.org/dc/terms/medium> <http://purl.org/lobid/lv#Miscellaneous> .

java.lang.RuntimeException: org.openrdf.rio.RDFParseException: Not a valid (absolute) URI: dummy_subject [line 4]
	at de.hbz.lobid.helper.RdfUtils.readRdfToGraph(RdfUtils.java:54) ~[classes/:?]
	at de.hbz.lobid.helper.JsonConverter.convertLobidData(JsonConverter.java:91) ~[classes/:?]
	at org.lobid.resources.RdfModel2ElasticsearchEtikettJsonLd.toJson(RdfModel2ElasticsearchEtikettJsonLd.java:166) ~[classes/:?]
	at org.lobid.resources.RdfModel2ElasticsearchEtikettJsonLd.extractItemFromResourceModel(RdfModel2ElasticsearchEtikettJsonLd.java:115) ~[classes/:?]
	at org.lobid.resources.RdfModel2ElasticsearchEtikettJsonLd.process(RdfModel2ElasticsearchEtikettJsonLd.java:90) ~[classes/:?]
	at org.lobid.resources.RdfModel2ElasticsearchEtikettJsonLd.process(RdfModel2ElasticsearchEtikettJsonLd.java:42) ~[classes/:?]
	at org.lobid.resources.Triples2RdfModel.process(Triples2RdfModel.java:102) [classes/:?]
	at org.lobid.resources.Triples2RdfModel.process(Triples2RdfModel.java:36) [classes/:?]
	at org.lobid.resources.PipeEncodeTriples.endRecord(PipeEncodeTriples.java:206) [classes/:?]
	at org.culturegraph.mf.stream.pipe.AbstractStreamBatcher.endRecord(AbstractStreamBatcher.java:60) [metafacture-core-4.0.0-HBZ-SNAPSHOT.jar:?]
	at org.culturegraph.mf.morph.Metamorph.endRecord(Metamorph.java:233) [metafacture-core-4.0.0-HBZ-SNAPSHOT.jar:?]
	at org.culturegraph.mf.stream.converter.xml.AlephMabXmlHandler.endElement(AlephMabXmlHandler.java:67) [metafacture-core-4.0.0-HBZ-SNAPSHOT.jar:?]
--
```

An other case is the following:
```
WARN - Ignore building resource, because no describedBy found in [(_:genid-af7a5d0020484bc2b7854e416ea424e4-B05037f4e85da01ab33effb1fb17defa5, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, http://d-nb.info/gnd/4126111-2) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B05037f4e85da01ab33effb1fb17defa5, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, _:genid-af7a5d0020484bc2b7854e416ea424e4-Bf78af37b589f972d27e4e021825fef65) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B135811e891199de43189eb5fcbe02b7a, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, http://d-nb.info/gnd/4013134-8) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B135811e891199de43189eb5fcbe02b7a, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, _:genid-af7a5d0020484bc2b7854e416ea424e4-B2104fdc75c137628a2d80448da0e5c60) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B2104fdc75c137628a2d80448da0e5c60, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, _:genid-af7a5d0020484bc2b7854e416ea424e4-BBibliographie) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B2104fdc75c137628a2d80448da0e5c60, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, http://www.w3.org/1999/02/22-rdf-syntax-ns#nil) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B347e0b30b8330c773731c3bf620241ae, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, "http://d-nb.info/gnd/4070370-8, http://d-nb.info/gnd/4013134-8, Bibliographie") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B347e0b30b8330c773731c3bf620241ae, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, http://www.w3.org/1999/02/22-rdf-syntax-ns#nil) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B3f31cab0d8d57961c7a6de18b4b95359, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, "http://d-nb.info/gnd/4011889-7, http://d-nb.info/gnd/4126111-2, Zeitschrift") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B3f31cab0d8d57961c7a6de18b4b95359, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, _:genid-af7a5d0020484bc2b7854e416ea424e4-B347e0b30b8330c773731c3bf620241ae) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B451d4455fb7d2183bf11cbed5be03a52, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, http://d-nb.info/gnd/4070370-8) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B451d4455fb7d2183bf11cbed5be03a52, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, _:genid-af7a5d0020484bc2b7854e416ea424e4-B135811e891199de43189eb5fcbe02b7a) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B6e36811edbc1c18c4f8460637875f54f, http://schema.org/location, "Frankfurt am Main") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B6e36811edbc1c18c4f8460637875f54f, http://schema.org/publishedBy, "Buchhändler-Vereinigung") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B6e36811edbc1c18c4f8460637875f54f, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://schema.org/PublicationEvent) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B86d01568f0fc0a3912f10f7016204ae7, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, http://d-nb.info/gnd/4011889-7) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B86d01568f0fc0a3912f10f7016204ae7, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, _:genid-af7a5d0020484bc2b7854e416ea424e4-B05037f4e85da01ab33effb1fb17defa5) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B902X2D2, http://purl.org/dc/terms/subject, _:genid-af7a5d0020484bc2b7854e416ea424e4-B907X2D2) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B902X2D2, http://www.loc.gov/mads/rdf/v1#componentList, _:genid-af7a5d0020484bc2b7854e416ea424e4-B86d01568f0fc0a3912f10f7016204ae7) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B902X2D2, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://www.loc.gov/mads/rdf/v1#ComplexSubject) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B902X2D2, http://www.w3.org/2000/01/rdf-schema#label, "Deutschland, Bundesrepublik | Nationalbibliografie | Zeitschrift") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B907X2D2, http://purl.org/lobid/lv#subjectOrder, _:genid-af7a5d0020484bc2b7854e416ea424e4-B3f31cab0d8d57961c7a6de18b4b95359) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B907X2D2, http://www.loc.gov/mads/rdf/v1#componentList, _:genid-af7a5d0020484bc2b7854e416ea424e4-B451d4455fb7d2183bf11cbed5be03a52) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B907X2D2, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://www.loc.gov/mads/rdf/v1#ComplexSubject) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-B907X2D2, http://www.w3.org/2000/01/rdf-schema#label, "Deutsches Sprachgebiet | Druckwerk | Bibliographie") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BBibliographie, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://d-nb.info/standards/elementset/gnd#SubjectHeading) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BBibliographie, http://www.w3.org/2000/01/rdf-schema#label, "Bibliographie") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BZeitschrift, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://d-nb.info/standards/elementset/gnd#SubjectHeading) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BZeitschrift, http://www.w3.org/2000/01/rdf-schema#label, "Zeitschrift") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-Bf781b6e185d0a2a330599643bc0e90e7, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, _:genid-af7a5d0020484bc2b7854e416ea424e4-BhttpX3AX2FX2FdX2DnbX2EinfoX2FgndX2F7674X2D0httpX3AX2FX2FidX2ElocX2EgovX2FvocabularyX2FrelatorsX2Fctb) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-Bf781b6e185d0a2a330599643bc0e90e7, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, http://www.w3.org/1999/02/22-rdf-syntax-ns#nil) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-Bf78af37b589f972d27e4e021825fef65, http://www.w3.org/1999/02/22-rdf-syntax-ns#first, _:genid-af7a5d0020484bc2b7854e416ea424e4-BZeitschrift) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-Bf78af37b589f972d27e4e021825fef65, http://www.w3.org/1999/02/22-rdf-syntax-ns#rest, http://www.w3.org/1999/02/22-rdf-syntax-ns#nil) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BhttpX3AX2FX2FdX2DnbX2EinfoX2FgndX2F7674X2D0httpX3AX2FX2FidX2ElocX2EgovX2FvocabularyX2FrelatorsX2Fctb, http://id.loc.gov/ontologies/bibframe/agent, http://d-nb.info/gnd/7674-0) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BhttpX3AX2FX2FdX2DnbX2EinfoX2FgndX2F7674X2D0httpX3AX2FX2FidX2ElocX2EgovX2FvocabularyX2FrelatorsX2Fctb, http://id.loc.gov/ontologies/bibframe/contribution, _:genid-af7a5d0020484bc2b7854e416ea424e4-Bf781b6e185d0a2a330599643bc0e90e7) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BhttpX3AX2FX2FdX2DnbX2EinfoX2FgndX2F7674X2D0httpX3AX2FX2FidX2ElocX2EgovX2FvocabularyX2FrelatorsX2Fctb, http://id.loc.gov/ontologies/bibframe/role, http://id.loc.gov/vocabulary/relators/ctb) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BhttpX3AX2FX2FdX2DnbX2EinfoX2FgndX2F7674X2D0httpX3AX2FX2FidX2ElocX2EgovX2FvocabularyX2FrelatorsX2Fctb, http://purl.org/dc/terms/subject, _:genid-af7a5d0020484bc2b7854e416ea424e4-B902X2D2) [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BhttpX3AX2FX2FdX2DnbX2EinfoX2FgndX2F7674X2D0httpX3AX2FX2FidX2ElocX2EgovX2FvocabularyX2FrelatorsX2Fctb, http://purl.org/lobid/lv#contributorOrder, "http://d-nb.info/gnd/7674-0") [null], (_:genid-af7a5d0020484bc2b7854e416ea424e4-BhttpX3AX2FX2FdX2DnbX2EinfoX2FgndX2F7674X2D0httpX3AX2FX2FidX2ElocX2EgovX2FvocabularyX2FrelatorsX2Fctb, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://id.loc.gov/ontologies/bibframe/Contribution) [null], (http://d-nb.info/gnd/4011889-7, http://id.loc.gov/ontologies/bibframe/source, http://d-nb.info/gnd/7749153-1) [null], (http://d-nb.info/gnd/4011889-7, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://d-nb.info/standards/elementset/gnd#PlaceOrGeographicName) [null], (http://d-nb.info/gnd/4011889-7, http://www.w3.org/2000/01/rdf-schema#label, "Deutschland, Bundesrepublik") [null], (http://d-nb.info/gnd/4013134-8, http://id.loc.gov/ontologies/bibframe/source, http://d-nb.info/gnd/7749153-1) [null], (http://d-nb.info/gnd/4013134-8, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://d-nb.info/standards/elementset/gnd#SubjectHeading) [null], (http://d-nb.info/gnd/4013134-8, http://www.w3.org/2000/01/rdf-schema#label, "Druckwerk") [null], (http://d-nb.info/gnd/4070370-8, http://id.loc.gov/ontologies/bibframe/source, http://d-nb.info/gnd/7749153-1) [null], (http://d-nb.info/gnd/4070370-8, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://d-nb.info/standards/elementset/gnd#PlaceOrGeographicName) [null], (http://d-nb.info/gnd/4070370-8, http://www.w3.org/2000/01/rdf-schema#label, "Deutsches Sprachgebiet") [null], (http://d-nb.info/gnd/4126111-2, http://id.loc.gov/ontologies/bibframe/source, http://d-nb.info/gnd/7749153-1) [null], (http://d-nb.info/gnd/4126111-2, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://d-nb.info/standards/elementset/gnd#SubjectHeading) [null], (http://d-nb.info/gnd/4126111-2, http://www.w3.org/2000/01/rdf-schema#label, "Nationalbibliografie") [null], (http://d-nb.info/gnd/7674-0, http://id.loc.gov/ontologies/bibframe/responsibilityStatement, "bearb. von d. Dt. Bibliothek, Frankfurt am Main") [null], (http://d-nb.info/gnd/7674-0, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://d-nb.info/standards/elementset/gnd#CorporateBody) [null], (http://d-nb.info/gnd/7674-0, http://www.w3.org/2000/01/rdf-schema#label, "Deutsche Bibliothek (Frankfurt am Main)") [null], (http://d-nb.info/gnd/7674-0, http://www.w3.org/2004/02/skos/core#altLabel, "DB") [null], (http://d-nb.info/gnd/7674-0, http://www.w3.org/2004/02/skos/core#altLabel, "Deutsche Bibliothek") [null], (http://d-nb.info/gnd/7674-0, http://www.w3.org/2004/02/skos/core#altLabel, "Gesamtarchiv und Nationalbibliographisches Informationszentrum") [null], (http://lobid.org/resources/#!, http://purl.org/dc/terms/medium, http://purl.org/lobid/lv#Miscellaneous) [null], (http://lobid.org/resources/#!, http://purl.org/dc/terms/title, "Deutsche Bibliographie") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Alemanha (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Alemania (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Allemagne (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Almanija (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Almāniyā (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "BRD") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "BRD (1949-1990)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Bondsrepubliek Duitsland (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Bundesrepublik Deutschland (1949-1990)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Deutscher Sprachraum") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Deutschland (1949-1990)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Deutschland (1949-1990, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Deutschsprachige Länder") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Deutschsprachiger Raum") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Deutschsprachiges Gebiet") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Druck (Druckwerk)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Drucke (Druckwerk)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Druckerzeugnis") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Druckschrift (Druckwerk)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Druckwerke") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "FRG") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Federal Republic of Germany (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Förbundsrepubliken Tyskland (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Förbundsrepublikken Tyskland (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Germany (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "NRF") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Nationalbibliographie") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Niemiecka Republika Federalna Niemiecka Republika Federalna") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Németországi Szövetségi Kőztársaság (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Publikation (Druckwerk)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "RFN") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Repubblica Federale di Germania (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Republic of Germany (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Republik Federasi Djerman (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Republika Federalna Niemiec (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "República Federal da Alemanha (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "República Federal de Alemania (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Retrospektive Nationalbibliografie") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "République Fédérale d'Allemagne (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Saksan Liittotasavalta (Deutschland, Bundesrepublik)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Schrift (Druckwerk)") [null], (http://lobid.org/resources/#!, http://purl.org/lobid/lv#subjectAltLabel, "Westdeutschland (Bundesrepublik, 1949-1990)") [null], (http://lobid.org/resources/#!, http://rdaregistry.info/Elements/u/P60517, "D, Fünfjahresverzeichnis") [null], (http://lobid.org/resources/#!, http://schema.org/publication, _:genid-af7a5d0020484bc2b7854e416ea424e4-B6e36811edbc1c18c4f8460637875f54f) [null], (http://lobid.org/resources/#!, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://purl.org/lobid/lv#Miscellaneous) [null]]
ERROR - Exception in <http://d-nb.info/gnd/4013134-8> <http://www.w3.org/2000/01/rdf-schema#label> "Druckwerk" .
```
I hope that the reason for this are two different definitions for `describedBy` (one with `@id` and one with `@itemId`.

**Comment by ChristophEwertowski** [comment]
To clarify: Both cases aren't in lobid. There is no resource from Bonn with `medium` `Miscellaneous` that fits and non with the publisher "Buchhändler-Vereinigung".

**Comment by dr0i** [comment]
I grepped the logs on a recent full transformation to see how many resources are affected:

> $ grep 'because no describedB' 20180328-0300-stage.startHbz02ToLobidResources.sh |wc -l
117
> $ grep "java.lang.RuntimeException: org.openrdf.rio.RDFParseException:" 20180328-0300-stage.startHbz02ToLobidResources.sh |wc -l
5

**Comment by ChristophEwertowski** [comment]
Error doesn't appear in log from 22nd of April (in fact every log after 28th of March doesn't have it). Closing this issue.
